version: '3.8'

services:
  web-server:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: diary_web-server
    ports:
      - "${PORT}:${PORT}"
    tty: true
    stdin_open: true
    env_file:
      - .env
    volumes:
      - ./:/app